In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth
import time

In [19]:
data = pd.read_csv("../datasets/ind.csv", sep = ";")

C:\Users\Budi\AppData\Local\Temp\ipykernel_18044\2080664985.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../datasets/ind.csv", sep = ";")

In [20]:
data1 = data[["BillNo", "Itemname", "Quantity"]].copy()

In [21]:
data1.head()

   BillNo                             Itemname  Quantity
0  536365   WHITE HANGING HEART T-LIGHT HOLDER         6
1  536365                  WHITE METAL LANTERN         6
2  536365       CREAM CUPID HEARTS COAT HANGER         8
3  536365  KNITTED UNION FLAG HOT WATER BOTTLE         6
4  536365       RED WOOLLY HOTTIE WHITE HEART.         6

In [28]:
#mengubah dari 0,0 menjadi 0
def one_hot_encoding(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
data1["Quantity"] = data1["Quantity"].apply(one_hot_encoding)

In [32]:
data1.head(100)

    BillNo                             Itemname  Quantity
0   536365   WHITE HANGING HEART T-LIGHT HOLDER         1
1   536365                  WHITE METAL LANTERN         1
2   536365       CREAM CUPID HEARTS COAT HANGER         1
3   536365  KNITTED UNION FLAG HOT WATER BOTTLE         1
4   536365       RED WOOLLY HOTTIE WHITE HEART.         1
..     ...                                  ...       ...
95  536378     LUNCH BOX WITH CUTLERY RETROSPOT         1
96  536378      PACK OF 72 RETROSPOT CAKE CASES         1
97  536378       PACK OF 60 DINOSAUR CAKE CASES         1
98  536378   PACK OF 60 PINK PAISLEY CAKE CASES         1
99  536378          60 TEATIME FAIRY CAKE CASES         1

[100 rows x 3 columns]

In [34]:
data1.to_csv("../datasets/datasets2Encode.csv", index=False)

In [35]:
item_count_pivot = data1.pivot_table(index='BillNo' , columns='Itemname', values='Quantity').fillna(0)

In [36]:
item_count_pivot.head()

Itemname,*Boombox Ipod Classic,*USB Office Mirror Ball,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
BillNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Itemname,*Boombox Ipod Classic,*USB Office Mirror Ball,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
BillNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572057,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
572058,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
toss = basket[]